# Copyright (c) 2025 - 2026 Chair for Design Automation, TUM
# Copyright (c) 2025 - 2026 Munich Quantum Software Company GmbH
# All rights reserved.
#
# SPDX-License-Identifier: MIT
#
# Licensed under the MIT License

"""Tests for MQT plugin execution with PennyLane and Catalyst.

These tests check that the MQT plugin conversion passes execute successfully
for various gate categories, mirroring the MLIR conversion tests. They verify
that the full lossless roundtrip (CatalystQuantum → QCO → CatalystQuantum)
works correctly. The tests use FileCheck (from LLVM) to verify the generated MLIR output.

Environment Variables:
    FILECHECK_PATH: Optional path to FileCheck binary if not in PATH
"""

from __future__ import annotations

import os
import shutil
import subprocess
import tempfile
from functools import lru_cache
from pathlib import Path
from typing import Any

import pennylane as qml
import pytest
from catalyst.passes import apply_pass

from mqt.core.plugins.catalyst import get_catalyst_plugin_abs_path, get_device

# Default pipeline for roundtrip conversion tests
DEFAULT_PIPELINE = [
    ("Init", ["builtin.module(canonicalize)"]),  # Trick to get initial CatalystQuantum MLIR
    ("ToQCO", ["builtin.module(catalystquantum-to-qco)"]),
    ("ToCatalystQuantum", ["builtin.module(qco-to-catalystquantum)"]),
]

# Standard MLIR file names generated by Catalyst
MLIR_FILE_INIT = "1_AfterInit.mlir"
MLIR_FILE_TO_QCO = "2_AfterToQCO.mlir"
MLIR_FILE_TO_CATALYST = "3_AfterToCatalystQuantum.mlir"
MQT_PLUGIN_PATH = get_catalyst_plugin_abs_path()


@pytest.fixture
def _isolated_working_directory(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    """Keep Catalyst intermediate files outside the source tree."""
    monkeypatch.chdir(tmp_path)


@lru_cache(maxsize=1)
def _get_filecheck() -> str | None:
    """Locate the FileCheck binary. Caches the result for future calls.

    Returns:
        The path to the FileCheck binary, or None if not found.
    """
    return _find_filecheck()


def _find_filecheck() -> str | None:
    candidates: list[Path] = []

    # 1. Explicit override (if CI ever sets it)
    if os.environ.get("FILECHECK_PATH"):
        candidates.append(Path(os.environ["FILECHECK_PATH"]))

    # 2. LLVM install prefix (best signal)
    if os.environ.get("LLVM_INSTALL_PREFIX"):
        candidates.append(Path(os.environ["LLVM_INSTALL_PREFIX"]) / "bin" / "FileCheck")

    # 3. LLVM_ROOT (common in setup-mlir)
    if os.environ.get("LLVM_ROOT"):
        candidates.append(Path(os.environ["LLVM_ROOT"]) / "bin" / "FileCheck")

    # 4. CMake-style LLVM_DIR
    if os.environ.get("LLVM_DIR"):
        candidates.append(Path(os.environ["LLVM_DIR"]) / ".." / ".." / ".." / "bin" / "FileCheck")

    # 5. CMake-style MLIR_DIR
    if os.environ.get("MLIR_DIR"):
        candidates.append(Path(os.environ["MLIR_DIR"]) / ".." / ".." / ".." / "bin" / "FileCheck")

    # 6. PATH (last resort)
    path_hit = shutil.which("FileCheck")
    if path_hit:
        candidates.append(Path(path_hit))

    for c in candidates:
        if c.exists() and c.is_file():
            return str(c.resolve())

    return None


def _run_filecheck(
    mlir_content: str,
    check_patterns: str,
    test_name: str = "test",
) -> None:
    """Run FileCheck on MLIR content using CHECK patterns from a string.

    Args:
        mlir_content: The MLIR output to verify
        check_patterns: String containing FileCheck directives (lines starting with // CHECK)
        test_name: Name of the test (for error messages)

    Raises:
        RuntimeError: If FileCheck is not found
        AssertionError: If FileCheck validation fails
    """
    filecheck = _get_filecheck()

    if filecheck is None:
        msg = (
            "FileCheck not found.\n"
            "Tried FILECHECK_PATH, LLVM_INSTALL_PREFIX, LLVM_ROOT, "
            "LLVM_DIR, MLIR_DIR, and PATH.\n"
            "Ensure LLVM is available or disable FileCheck-based tests."
        )
        raise RuntimeError(msg)

    with tempfile.NamedTemporaryFile(
        encoding="utf-8",
        mode="w",
        suffix=".mlir",
        delete=False,
    ) as check_file:
        check_file.write(check_patterns)
        check_file_path = check_file.name

    try:
        result = subprocess.run(  # ruff:ignore[subprocess-without-shell-equals-true]
            [filecheck, check_file_path, "--allow-unused-prefixes"],
            input=mlir_content.encode(),
            capture_output=True,
            check=False,
            timeout=30,
        )

        if result.returncode != 0:
            stderr = result.stderr.decode(errors="replace") if result.stderr else "Unknown error"
            msg = (
                f"FileCheck failed for {test_name}:\n"
                f"{stderr}\n\n"
                f"MLIR Output (first 2000 chars):\n"
                f"{mlir_content[:2000]}..."
            )
            raise AssertionError(msg)
    finally:
        Path(check_file_path).unlink()


def _get_mlir_file_paths() -> tuple[Path, Path, Path]:
    """Get paths to the three expected MLIR intermediate files.

    Returns:
        Tuple of (catalyst_mlir, mlir_to_qco, mlir_to_catalyst) paths

    Raises:
        RuntimeError: If Catalyst did not create exactly one workspace.
    """
    workspaces = [path for path in Path.cwd().glob("module*") if path.is_dir()]
    if len(workspaces) != 1:
        msg = f"Expected one Catalyst workspace, found: {[path.name for path in workspaces]}"
        raise RuntimeError(msg)
    mlir_dir = workspaces[0]
    return (
        mlir_dir / MLIR_FILE_INIT,
        mlir_dir / MLIR_FILE_TO_QCO,
        mlir_dir / MLIR_FILE_TO_CATALYST,
    )


def _verify_and_read_mlir_files() -> tuple[str, str, str]:
    """Verify MLIR files exist and read their contents.

    Returns:
        Tuple of (mlir_before, mlir_after_qco, mlir_after_roundtrip) as strings

    Raises:
        FileNotFoundError: If any expected MLIR file is missing
    """
    catalyst_mlir, mlir_to_qco, mlir_to_catalyst = _get_mlir_file_paths()

    if not catalyst_mlir.exists() or not mlir_to_qco.exists() or not mlir_to_catalyst.exists():
        mlir_dir = catalyst_mlir.parent
        available_files = list(mlir_dir.glob("*.mlir"))
        msg = f"Expected MLIR files not found in {mlir_dir}.\nAvailable files: {[f.name for f in available_files]}"
        raise FileNotFoundError(msg)

    mlir_before = catalyst_mlir.read_text(encoding="utf-8")
    mlir_after_qco = mlir_to_qco.read_text(encoding="utf-8")
    mlir_after_roundtrip = mlir_to_catalyst.read_text(encoding="utf-8")

    return mlir_before, mlir_after_qco, mlir_after_roundtrip


def _verify_roundtrip(
    test_name: str,
    check_before: str,
    check_qco: str,
    check_after: str,
) -> None:
    """Verify MLIR roundtrip conversion using FileCheck.

    Args:
        test_name: Name of the test (for error messages)
        check_before: FileCheck patterns for initial CatalystQuantum MLIR
        check_qco: FileCheck patterns for CatalystQuantum → QCO conversion
        check_after: FileCheck patterns for QCO → CatalystQuantum conversion
    """
    mlir_before, mlir_after_qco, mlir_after_roundtrip = _verify_and_read_mlir_files()

    _run_filecheck(mlir_before, check_before, f"{test_name}: CatalystQuantum")
    _run_filecheck(mlir_after_qco, check_qco, f"{test_name}: CatalystQuantum to QCO")
    _run_filecheck(mlir_after_roundtrip, check_after, f"{test_name}: QCO to CatalystQuantum")


@pytest.mark.usefixtures("_isolated_working_directory")
def test_paulix_roundtrip() -> None:
    """Test roundtrip conversion of the PauliX gate."""

    @apply_pass("qco-to-catalystquantum")
    @apply_pass("catalystquantum-to-qco")
    @qml.qnode(get_device("lightning.qubit", wires=2))
    def circuit() -> None:
        # Non-controlled
        qml.X(wires=0)
        qml.PauliX(wires=0)
        # Controlled
        qml.ctrl(qml.PauliX, control=1)(wires=0)
        qml.CNOT(wires=[1, 0])

    @qml.qjit(
        target="mlir",
        pipelines=DEFAULT_PIPELINE,
        autograph=True,
        keep_intermediate=2,
        pass_plugins={MQT_PLUGIN_PATH},
        dialect_plugins={MQT_PLUGIN_PATH},
    )
    def module() -> Any:  # ruff:ignore[any-type]
        return circuit()

    # Verify the roundtrip completes successfully
    assert module.mlir_opt

    # Verify original CatalystQuantum
    check_mlir_before = """
      //CHECK: %[[Q0_1:.*]] = quantum.custom "PauliX"() %[[Q0_0:.*]] : !quantum.bit
      //CHECK: %[[Q0_2:.*]] = quantum.custom "PauliX"() %[[Q0_1:.*]] : !quantum.bit
      //CHECK: %[[Q10_0:.*]]:2 = quantum.custom "CNOT"() %[[Q1_0:.*]], %[[Q0_1:.*]] : !quantum.bit, !quantum.bit
      //CHECK: %[[Q10_0:.*]]:2 = quantum.custom "CNOT"() %[[Q10_0:.*]]#0, %[[Q10_0:.*]]#1 : !quantum.bit, !quantum.bit
    """

    # Verify CatalystQuantum → QCO conversion
    check_after_qco = """
      //CHECK: qco.x
      //CHECK: qco.x
      //CHECK: qco.ctrl
      //CHECK: qco.x
      //CHECK: qco.ctrl
      //CHECK: qco.x
    """

    # Verify QCO → CatalystQuantum conversion
    check_after_catalyst = """
        //CHECK: quantum.custom "PauliX"
        //CHECK: quantum.custom "PauliX"
        //CHECK: quantum.custom "CNOT"
        //CHECK: quantum.custom "CNOT"
    """

    _verify_roundtrip("PauliX", check_mlir_before, check_after_qco, check_after_catalyst)


@pytest.mark.usefixtures("_isolated_working_directory")
def test_pauliy_roundtrip() -> None:
    """Test roundtrip conversion of the PauliY gate."""

    @apply_pass("qco-to-catalystquantum")
    @apply_pass("catalystquantum-to-qco")
    @qml.qnode(get_device("lightning.qubit", wires=2))
    def circuit() -> None:
        # Non-controlled
        qml.Y(wires=0)
        qml.PauliY(wires=0)
        # Controlled
        qml.ctrl(qml.PauliY, control=1)(wires=0)
        qml.CY(wires=[1, 0])

    @qml.qjit(
        target="mlir",
        pipelines=DEFAULT_PIPELINE,
        autograph=True,
        keep_intermediate=2,
        pass_plugins={MQT_PLUGIN_PATH},
        dialect_plugins={MQT_PLUGIN_PATH},
    )
    def module() -> Any:  # ruff:ignore[any-type]
        return circuit()

    # Verify the roundtrip completes successfully
    assert module.mlir_opt

    # Verify original CatalystQuantum
    check_mlir_before = """
        //CHECK: %[[Q0_1:.*]] = quantum.custom "PauliY"() %[[Q0_0:.*]] : !quantum.bit
        //CHECK: %[[Q0_2:.*]] = quantum.custom "PauliY"() %[[Q0_1:.*]] : !quantum.bit
        //CHECK: %[[Q10_0:.*]]:2 = quantum.custom "CY"() %[[Q1_0:.*]], %[[Q0_2:.*]] : !quantum.bit, !quantum.bit
        //CHECK: %[[Q10_0:.*]]:2 = quantum.custom "CY"() %[[Q10_0:.*]]#0, %[[Q10_0:.*]]#1 : !quantum.bit, !quantum.bit
    """

    # Verify CatalystQuantum → QCO conversion
    check_after_qco = """
        //CHECK: qco.y
        //CHECK: qco.y
        //CHECK: qco.ctrl
        //CHECK: qco.y
        //CHECK: qco.ctrl
        //CHECK: qco.y
    """

    # Verify QCO → CatalystQuantum conversion
    check_after_catalyst = """
        //CHECK: quantum.custom "PauliY"
        //CHECK: quantum.custom "PauliY"
        //CHECK: quantum.custom "CY"
        //CHECK: quantum.custom "CY"
    """

    _verify_roundtrip("PauliY", check_mlir_before, check_after_qco, check_after_catalyst)


@pytest.mark.usefixtures("_isolated_working_directory")
def test_pauliz_roundtrip() -> None:
    """Test roundtrip conversion of the PauliZ gate."""

    @apply_pass("qco-to-catalystquantum")
    @apply_pass("catalystquantum-to-qco")
    @qml.qnode(get_device("lightning.qubit", wires=2))
    def circuit() -> None:
        # Non-controlled
        qml.Z(wires=0)
        qml.PauliZ(wires=0)
        # Controlled
        qml.ctrl(qml.PauliZ, control=1)(wires=0)
        qml.CZ(wires=[1, 0])

    @qml.qjit(
        target="mlir",
        pipelines=DEFAULT_PIPELINE,
        autograph=True,
        keep_intermediate=2,
        pass_plugins={MQT_PLUGIN_PATH},
        dialect_plugins={MQT_PLUGIN_PATH},
    )
    def module() -> Any:  # ruff:ignore[any-type]
        return circuit()

    # Verify the roundtrip completes successfully
    assert module.mlir_opt

    # Verify original CatalystQuantum
    check_mlir_before = """
        //CHECK: %[[Q0_1:.*]] = quantum.custom "PauliZ"() %[[Q0_0:.*]] : !quantum.bit
        //CHECK: %[[Q0_2:.*]] = quantum.custom "PauliZ"() %[[Q0_1:.*]] : !quantum.bit
        //CHECK: %[[Q10_0:.*]]:2 = quantum.custom "CZ"() %[[Q1_0:.*]], %[[Q0_2:.*]] : !quantum.bit, !quantum.bit
        //CHECK: %[[Q10_0:.*]]:2 = quantum.custom "CZ"() %[[Q10_0:.*]]#0, %[[Q10_0:.*]]#1 : !quantum.bit, !quantum.bit
    """

    # Verify CatalystQuantum → QCO conversion
    check_after_qco = """
        //CHECK: qco.z
        //CHECK: qco.z
        //CHECK: qco.ctrl
        //CHECK: qco.z
        //CHECK: qco.ctrl
        //CHECK: qco.z
    """

    # Verify QCO → CatalystQuantum conversion
    check_after_catalyst = """
        //CHECK: quantum.custom "PauliZ"
        //CHECK: quantum.custom "PauliZ"
        //CHECK: quantum.custom "CZ"
        //CHECK: quantum.custom "CZ"
    """

    _verify_roundtrip("PauliZ", check_mlir_before, check_after_qco, check_after_catalyst)


@pytest.mark.usefixtures("_isolated_working_directory")
def test_hadamard_roundtrip() -> None:
    """Test roundtrip conversion of the Hadamard gate."""

    @apply_pass("qco-to-catalystquantum")
    @apply_pass("catalystquantum-to-qco")
    @qml.qnode(get_device("lightning.qubit", wires=2))
    def circuit() -> None:
        qml.Hadamard(wires=0)
        qml.ctrl(qml.Hadamard, control=1)(wires=0)
        qml.CH(wires=[1, 0])

    @qml.qjit(
        target="mlir",
        pipelines=DEFAULT_PIPELINE,
        autograph=True,
        keep_intermediate=2,
        pass_plugins={MQT_PLUGIN_PATH},
        dialect_plugins={MQT_PLUGIN_PATH},
    )
    def module() -> Any:  # ruff:ignore[any-type]
        return circuit()

    # Verify the roundtrip completes successfully
    assert module.mlir_opt

    check_mlir_before = """
        //CHECK: %[[Q0_1:.*]] = quantum.custom "Hadamard"() %[[Q0_0:.*]] : !quantum.bit
        //CHECK: %[[Q0_2:.*]], %[[Q1_1:.*]] = quantum.custom "Hadamard"() %[[Q0_1:.*]] ctrls(%[[Q1_0:.*]]) ctrlvals(%true{{(_[0-9]+)?}}) : !quantum.bit ctrls !quantum.bit
        //CHECK: %[[Q0_3:.*]], %[[Q1_2:.*]] = quantum.custom "Hadamard"() %[[Q0_2:.*]] ctrls(%[[Q1_1:.*]]) ctrlvals(%true{{(_[0-9]+)?}}) : !quantum.bit ctrls !quantum.bit
    """

    check_after_qco = """
        //CHECK: qco.h
        //CHECK: qco.ctrl
        //CHECK: qco.h
        //CHECK: qco.ctrl
        //CHECK: qco.h
    """

    check_after_catalyst = """
        //CHECK: quantum.custom "Hadamard"
        //CHECK: quantum.custom "Hadamard"
        //CHECK: quantum.custom "Hadamard"
    """

    _verify_roundtrip("Hadamard", check_mlir_before, check_after_qco, check_after_catalyst)


@pytest.mark.usefixtures("_isolated_working_directory")
def test_s_gate_roundtrip() -> None:
    """Test roundtrip conversion of the S gate."""

    @apply_pass("qco-to-catalystquantum")
    @apply_pass("catalystquantum-to-qco")
    @qml.qnode(get_device("lightning.qubit", wires=2))
    def circuit() -> None:
        qml.S(wires=0)
        qml.adjoint(qml.S(wires=0))  # ty: ignore[no-matching-overload]
        qml.ctrl(qml.S, control=1)(wires=0)

    @qml.qjit(
        target="mlir",
        pipelines=DEFAULT_PIPELINE,
        autograph=True,
        keep_intermediate=2,
        pass_plugins={MQT_PLUGIN_PATH},
        dialect_plugins={MQT_PLUGIN_PATH},
    )
    def module() -> Any:  # ruff:ignore[any-type]
        return circuit()

    # Verify the roundtrip completes successfully
    assert module.mlir_opt

    check_mlir_before = """
      //CHECK: %[[Q0_1:.*]] = quantum.custom "S"() %[[Q0_0:.*]] : !quantum.bit
      //CHECK: %[[Q0_2:.*]] = quantum.custom "S"() %[[Q0_1:.*]] adj : !quantum.bit
      //CHECK: %[[Q0_3:.*]], %[[Q1_1:.*]] = quantum.custom "S"() %[[Q0_2:.*]] ctrls(%[[Q1_0:.*]]) ctrlvals(%true{{(_[0-9]+)?}}) : !quantum.bit ctrls !quantum.bit
    """

    check_after_qco = """
      //CHECK: qco.s
      //CHECK: qco.inv
      //CHECK: qco.s
      //CHECK: qco.ctrl
      //CHECK: qco.s
    """

    check_after_catalyst = """
      //CHECK: quantum.custom "S"
      //CHECK: quantum.custom "S"{{.*}} adj
      //CHECK: quantum.custom "S"
    """

    _verify_roundtrip("S", check_mlir_before, check_after_qco, check_after_catalyst)


@pytest.mark.usefixtures("_isolated_working_directory")
def test_t_gate_roundtrip() -> None:
    """Test roundtrip conversion of the T gate."""

    @apply_pass("qco-to-catalystquantum")
    @apply_pass("catalystquantum-to-qco")
    @qml.qnode(get_device("lightning.qubit", wires=2))
    def circuit() -> None:
        qml.T(wires=0)
        qml.adjoint(qml.T(wires=0))  # ty: ignore[no-matching-overload]
        qml.ctrl(qml.T, control=1)(wires=0)

    @qml.qjit(
        target="mlir",
        pipelines=DEFAULT_PIPELINE,
        autograph=True,
        keep_intermediate=2,
        pass_plugins={MQT_PLUGIN_PATH},
        dialect_plugins={MQT_PLUGIN_PATH},
    )
    def module() -> Any:  # ruff:ignore[any-type]
        return circuit()

    # Verify the roundtrip completes successfully
    assert module.mlir_opt

    check_mlir_before = """
        //CHECK: %[[Q0_1:.*]] = quantum.custom "T"() %[[Q0_0:.*]] : !quantum.bit
        //CHECK: %[[Q0_2:.*]] = quantum.custom "T"() %[[Q0_1:.*]] adj : !quantum.bit
        //CHECK: %[[Q0_3:.*]], %[[Q1_1:.*]] = quantum.custom "T"() %[[Q0_2:.*]] ctrls(%[[Q1_0:.*]]) ctrlvals(%true{{(_[0-9]+)?}}) : !quantum.bit ctrls !quantum.bit
    """

    check_after_qco = """
        //CHECK: qco.t
        //CHECK: qco.inv
        //CHECK: qco.t
        //CHECK: qco.ctrl
        //CHECK: qco.t
    """

    check_after_catalyst = """
      //CHECK: quantum.custom "T"
      //CHECK: quantum.custom "T"{{.*}} adj
      //CHECK: quantum.custom "T"
    """

    _verify_roundtrip("T", check_mlir_before, check_after_qco, check_after_catalyst)


@pytest.mark.usefixtures("_isolated_working_directory")
def test_rx_gate_roundtrip() -> None:
    """Test roundtrip conversion of the RX gate."""

    @apply_pass("qco-to-catalystquantum")
    @apply_pass("catalystquantum-to-qco")
    @qml.qnode(get_device("lightning.qubit", wires=3))
    def circuit() -> None:
        qml.RX(0.5, wires=0)
        qml.ctrl(qml.RX, control=1)(0.5, wires=0)
        qml.CRX(0.5, wires=[1, 0])
        qml.ctrl(qml.CRX, control=2)(0.5, wires=[1, 0])

    @qml.qjit(
        target="mlir",
        pipelines=DEFAULT_PIPELINE,
        autograph=True,
        keep_intermediate=2,
        pass_plugins={MQT_PLUGIN_PATH},
        dialect_plugins={MQT_PLUGIN_PATH},
    )
    def module() -> Any:  # ruff:ignore[any-type]
        return circuit()

    # Verify the roundtrip completes successfully
    mlir_opt = module.mlir_opt
    assert mlir_opt

    check_mlir_before = """
        //CHECK: %[[Q0_1:.*]] = quantum.custom "RX"({{.*}}) %[[Q0_0:.*]] : !quantum.bit
        //CHECK: %[[Q10_0:.*]]:2 = quantum.custom "CRX"({{.*}}) %[[Q1_0:.*]], %[[Q0_1:.*]] : !quantum.bit, !quantum.bit
        //CHECK: %[[Q11_0:.*]]:2 = quantum.custom "CRX"({{.*}}) %[[Q10_0]]#0, %[[Q10_0:.*]]#1 : !quantum.bit, !quantum.bit
        //CHECK: %[[Q0_2:.*]], %[[Q21_0:.*]]:2 = quantum.custom "RX"({{.*}}) %[[Q11_0:.*]]#1 ctrls(%[[Q2_0:.*]], %[[Q11_0:.*]]#0) ctrlvals({{.*}}, {{.*}}) : !quantum.bit ctrls !quantum.bit, !quantum.bit
    """

    check_after_qco = """
        //CHECK: qco.rx
        //CHECK: qco.ctrl
        //CHECK: qco.rx
        //CHECK: qco.ctrl
        //CHECK: qco.rx
        //CHECK: qco.ctrl
        //CHECK: qco.rx
    """

    check_after_catalyst = """
        //CHECK: quantum.custom "RX"
        //CHECK: quantum.custom "CRX"
        //CHECK: quantum.custom "CRX"
        //CHECK: quantum.custom "RX"
    """
    _verify_roundtrip("RX", check_mlir_before, check_after_qco, check_after_catalyst)


@pytest.mark.usefixtures("_isolated_working_directory")
def test_ry_gate_roundtrip() -> None:
    """Test roundtrip conversion of the RY gate."""

    @apply_pass("qco-to-catalystquantum")
    @apply_pass("catalystquantum-to-qco")
    @qml.qnode(get_device("lightning.qubit", wires=3))
    def circuit() -> None:
        qml.RY(0.5, wires=0)
        qml.ctrl(qml.RY, control=1)(0.5, wires=0)
        qml.CRY(0.5, wires=[1, 0])
        qml.ctrl(qml.CRY, control=2)(0.5, wires=[1, 0])

    @qml.qjit(
        target="mlir",
        pipelines=DEFAULT_PIPELINE,
        autograph=True,
        keep_intermediate=2,
        pass_plugins={MQT_PLUGIN_PATH},
        dialect_plugins={MQT_PLUGIN_PATH},
    )
    def module() -> Any:  # ruff:ignore[any-type]
        return circuit()

    # Verify the roundtrip completes successfully
    mlir_opt = module.mlir_opt
    assert mlir_opt

    check_mlir_before = """
        //CHECK: %[[Q0_1:.*]] = quantum.custom "RY"({{.*}}) %[[Q0_0:.*]] : !quantum.bit
        //CHECK: %[[Q10_0:.*]]:2 = quantum.custom "CRY"({{.*}}) %[[Q1_0:.*]], %[[Q0_1:.*]] : !quantum.bit, !quantum.bit
        //CHECK: %[[Q11_0:.*]]:2 = quantum.custom "CRY"({{.*}}) %[[Q10_0]]#0, %[[Q10_0:.*]]#1 : !quantum.bit, !quantum.bit
        //CHECK: %[[Q0_2:.*]], %[[Q21_0:.*]]:2 = quantum.custom "RY"({{.*}}) %[[Q11_0:.*]]#1 ctrls(%[[Q2_0:.*]], %[[Q11_0:.*]]#0) ctrlvals({{.*}}, {{.*}}) : !quantum.bit ctrls !quantum.bit, !quantum.bit
    """

    check_after_qco = """
        //CHECK: qco.ry
        //CHECK: qco.ctrl
        //CHECK: qco.ry
        //CHECK: qco.ctrl
        //CHECK: qco.ry
        //CHECK: qco.ctrl
        //CHECK: qco.ry
    """

    check_after_catalyst = """
        //CHECK: quantum.custom "RY"
        //CHECK: quantum.custom "CRY"
        //CHECK: quantum.custom "CRY"
        //CHECK: quantum.custom "RY"
    """
    _verify_roundtrip("RY", check_mlir_before, check_after_qco, check_after_catalyst)


@pytest.mark.usefixtures("_isolated_working_directory")
def test_rz_gate_roundtrip() -> None:
    """Test roundtrip conversion of the RZ gate."""

    @apply_pass("qco-to-catalystquantum")
    @apply_pass("catalystquantum-to-qco")
    @qml.qnode(get_device("lightning.qubit", wires=3))
    def circuit() -> None:
        qml.RZ(0.5, wires=0)
        qml.ctrl(qml.RZ, control=1)(0.5, wires=0)
        qml.CRZ(0.5, wires=[1, 0])
        qml.ctrl(qml.CRZ, control=2)(0.5, wires=[1, 0])

    @qml.qjit(
        target="mlir",
        pipelines=DEFAULT_PIPELINE,
        autograph=True,
        keep_intermediate=2,
        pass_plugins={MQT_PLUGIN_PATH},
        dialect_plugins={MQT_PLUGIN_PATH},
    )
    def module() -> Any:  # ruff:ignore[any-type]
        return circuit()

    # Verify the roundtrip completes successfully
    assert module.mlir_opt

    check_mlir_before = """
        //CHECK: %[[Q0_1:.*]] = quantum.custom "RZ"({{.*}}) %[[Q0_0:.*]] : !quantum.bit
        //CHECK: %[[Q10_0:.*]]:2 = quantum.custom "CRZ"({{.*}}) %[[Q1_0:.*]], %[[Q0_1:.*]] : !quantum.bit, !quantum.bit
        //CHECK: %[[Q11_0:.*]]:2 = quantum.custom "CRZ"({{.*}}) %[[Q10_0]]#0, %[[Q10_0:.*]]#1 : !quantum.bit, !quantum.bit
        //CHECK: %[[Q0_2:.*]], %[[Q21_0:.*]]:2 = quantum.custom "RZ"({{.*}}) %[[Q11_0:.*]]#1 ctrls(%[[Q2_0:.*]], %[[Q11_0]]#0) ctrlvals({{.*}}, {{.*}}) : !quantum.bit ctrls !quantum.bit, !quantum.bit
    """

    check_after_qco = """
        //CHECK: qco.rz
        //CHECK: qco.ctrl
        //CHECK: qco.rz
        //CHECK: qco.ctrl
        //CHECK: qco.rz
        //CHECK: qco.ctrl
        //CHECK: qco.rz
    """

    check_after_catalyst = """
        //CHECK: quantum.custom "RZ"
        //CHECK: quantum.custom "CRZ"
        //CHECK: quantum.custom "CRZ"
        //CHECK: quantum.custom "RZ"
    """

    _verify_roundtrip("RZ", check_mlir_before, check_after_qco, check_after_catalyst)


@pytest.mark.usefixtures("_isolated_working_directory")
def test_phaseshift_gate_roundtrip() -> None:
    """Test roundtrip conversion of the PhaseShift gate."""

    @apply_pass("qco-to-catalystquantum")
    @apply_pass("catalystquantum-to-qco")
    @qml.qnode(get_device("lightning.qubit", wires=2))
    def circuit() -> None:
        qml.PhaseShift(0.5, wires=0)
        qml.ctrl(qml.PhaseShift, control=1)(0.5, wires=0)
        qml.ControlledPhaseShift(0.5, wires=[1, 0])

    @qml.qjit(
        target="mlir",
        pipelines=DEFAULT_PIPELINE,
        autograph=True,
        keep_intermediate=2,
        pass_plugins={MQT_PLUGIN_PATH},
        dialect_plugins={MQT_PLUGIN_PATH},
    )
    def module() -> Any:  # ruff:ignore[any-type]
        return circuit()

    # Verify the roundtrip completes successfully
    assert module.mlir_opt

    check_mlir_before = """
        //CHECK: %[[Q0_1:.*]] = quantum.custom "PhaseShift"({{.*}}) %[[Q0_0:.*]] : !quantum.bit
        //CHECK: %[[Q10_0:.*]]:2 = quantum.custom "ControlledPhaseShift"({{.*}}) %[[Q1_0:.*]], %[[Q0_1:.*]] : !quantum.bit, !quantum.bit
        //CHECK: %[[Q11_0:.*]]:2 = quantum.custom "ControlledPhaseShift"({{.*}}) %[[Q10_0:.*]]#0, %[[Q10_0:.*]]#1 : !quantum.bit, !quantum.bit
    """

    check_after_qco = """
        //CHECK: qco.p
        //CHECK: qco.ctrl
        //CHECK: qco.p
        //CHECK: qco.ctrl
        //CHECK: qco.p
    """

    check_after_catalyst = """
        //CHECK: quantum.custom "PhaseShift"
        //CHECK: quantum.custom "ControlledPhaseShift"
        //CHECK: quantum.custom "ControlledPhaseShift"
    """

    _verify_roundtrip("PhaseShift", check_mlir_before, check_after_qco, check_after_catalyst)


@pytest.mark.usefixtures("_isolated_working_directory")
def test_swap_gate_roundtrip() -> None:
    """Test roundtrip conversion of the SWAP gate."""

    @apply_pass("qco-to-catalystquantum")
    @apply_pass("catalystquantum-to-qco")
    @qml.qnode(get_device("lightning.qubit", wires=3))
    def circuit() -> None:
        qml.SWAP(wires=[0, 1])
        qml.ctrl(qml.SWAP, control=2)(wires=[0, 1])
        qml.CSWAP(wires=[2, 0, 1])

    @qml.qjit(
        target="mlir",
        pipelines=DEFAULT_PIPELINE,
        autograph=True,
        keep_intermediate=2,
        pass_plugins={MQT_PLUGIN_PATH},
        dialect_plugins={MQT_PLUGIN_PATH},
    )
    def module() -> Any:  # ruff:ignore[any-type]
        return circuit()

    # Verify the roundtrip completes successfully
    assert module.mlir_opt

    check_mlir_before = """
        //CHECK: %[[Q01_0:.*]]:2 = quantum.custom "SWAP"() %[[Q0_0:.*]], %[[Q1_0:.*]] : !quantum.bit, !quantum.bit
        //CHECK: %[[Q201_0:.*]]:3 = quantum.custom "CSWAP"() %[[Q2_0:.*]], %[[Q01_0:.*]]#0, %[[Q01_0:.*]]#1 : !quantum.bit, !quantum.bit, !quantum.bit
        //CHECK: %[[Q201_1:.*]]:3 = quantum.custom "CSWAP"() %[[Q201_0:.*]]#0, %[[Q201_0:.*]]#1, %[[Q201_0:.*]]#2 : !quantum.bit, !quantum.bit, !quantum.bit
    """

    check_after_qco = """
        //CHECK: qco.swap
        //CHECK: qco.ctrl
        //CHECK: qco.swap
        //CHECK: qco.ctrl
        //CHECK: qco.swap
    """

    check_after_catalyst = """
        //CHECK: quantum.custom "SWAP"
        //CHECK: quantum.custom "CSWAP"
        //CHECK: quantum.custom "CSWAP"
    """

    _verify_roundtrip("SWAP", check_mlir_before, check_after_qco, check_after_catalyst)


@pytest.mark.usefixtures("_isolated_working_directory")
def test_toffoli_gate_roundtrip() -> None:
    """Test roundtrip conversion of the Toffoli gate."""

    @apply_pass("qco-to-catalystquantum")
    @apply_pass("catalystquantum-to-qco")
    @qml.qnode(get_device("lightning.qubit", wires=4))
    def circuit() -> None:
        qml.Toffoli(wires=[0, 1, 2])
        qml.ctrl(qml.Toffoli, control=3)(wires=[0, 1, 2])

    @qml.qjit(
        target="mlir",
        pipelines=DEFAULT_PIPELINE,
        autograph=True,
        keep_intermediate=2,
        pass_plugins={MQT_PLUGIN_PATH},
        dialect_plugins={MQT_PLUGIN_PATH},
    )
    def module() -> Any:  # ruff:ignore[any-type]
        return circuit()

    # Verify the roundtrip completes successfully
    assert module.mlir_opt

    check_mlir_before = """
        //CHECK: %[[Q012_0:.*]]:3 = quantum.custom "Toffoli"() %[[Q0_0:.*]], %[[Q1_0:.*]], %[[Q2_0:.*]] : !quantum.bit, !quantum.bit, !quantum.bit
        //CHECK: %[[Q2_1:.*]], %[[Q301_0:.*]]:3 = quantum.custom "PauliX"() %[[Q012_0:.*]]#2 ctrls(%[[Q3_0:.*]], %[[Q012_0:.*]]#0, %[[Q012_0:.*]]#1) ctrlvals({{.*}}, {{.*}}, {{.*}}) : !quantum.bit ctrls !quantum.bit, !quantum.bit, !quantum.bit
    """

    check_after_qco = """
        //CHECK: qco.ctrl
        //CHECK: qco.x
        //CHECK: qco.ctrl
        //CHECK: qco.x
    """

    check_after_catalyst = """
        //CHECK: quantum.custom "Toffoli"
        //CHECK: quantum.custom "PauliX"
    """

    _verify_roundtrip("Toffoli", check_mlir_before, check_after_qco, check_after_catalyst)


@pytest.mark.usefixtures("_isolated_working_directory")
def test_qc_chained_roundtrip() -> None:
    """Execute CatalystQuantum through QCO, QC, and back."""

    def circuit_body() -> qml.measurements.ExpectationMP:
        qml.RY(0.3, wires=0)
        qml.CNOT(wires=[0, 1])
        qml.RZ(0.4, wires=1)
        return qml.expval(qml.PauliZ(wires=0))

    @qml.qnode(qml.device("lightning.qubit", wires=2))
    def reference_circuit() -> qml.measurements.ExpectationMP:
        return circuit_body()

    @apply_pass("qco-to-catalystquantum")
    @apply_pass("qc-to-qco")
    @apply_pass("qco-to-qc")
    @apply_pass("catalystquantum-to-qco")
    @qml.qnode(get_device("lightning.qubit", wires=2))
    def circuit() -> qml.measurements.ExpectationMP:
        return circuit_body()

    @qml.qjit(pass_plugins={MQT_PLUGIN_PATH}, dialect_plugins={MQT_PLUGIN_PATH})
    def executable() -> Any:  # ruff:ignore[any-type]
        return circuit()

    expected = float(reference_circuit())
    assert abs(expected) > 0.1
    assert float(executable()) == pytest.approx(expected)


@pytest.mark.usefixtures("_isolated_working_directory")
def test_issue_35_gate_roundtrip() -> None:
    """Execute the gate set from issue 35 through the QCO round trip."""

    def circuit_body() -> qml.measurements.ExpectationMP:
        qml.SX(wires=0)
        qml.ECR(wires=[0, 1])
        qml.SISWAP(wires=[1, 2])
        qml.Toffoli(wires=[0, 1, 2])
        qml.PauliRot(0.25, "IXYZ", wires=[0, 1, 2, 3])
        qml.MultiRZ(0.35, wires=[0, 1, 2])
        qml.U1(0.1, wires=0)
        qml.U2(0.2, 0.3, wires=1)
        qml.U3(0.4, 0.5, 0.6, wires=2)
        return qml.expval(qml.PauliX(wires=0))

    @qml.qnode(qml.device("lightning.qubit", wires=4))
    def reference_circuit() -> qml.measurements.ExpectationMP:
        return circuit_body()

    @apply_pass("qco-to-catalystquantum")
    @apply_pass("catalystquantum-to-qco")
    @qml.qnode(get_device("lightning.qubit", wires=4))
    def circuit() -> qml.measurements.ExpectationMP:
        return circuit_body()

    @qml.qjit(pass_plugins={MQT_PLUGIN_PATH}, dialect_plugins={MQT_PLUGIN_PATH})
    def executable() -> Any:  # ruff:ignore[any-type]
        return circuit()

    expected = float(reference_circuit())
    assert abs(expected) > 0.1
    assert float(executable()) == pytest.approx(expected)
