version: 2

formats:
  - htmlzip

sphinx:
  configuration: docs/conf.py

build:
  os: ubuntu-24.04
  tools:
    python: "3.13"
  apt_packages:
    - libmlir-19-dev
    - mlir-19-tools
    - clang-19
    - clang-tools-19
    - graphviz

python:
  install:
    - method: pip
      path: .
    - requirements: docs/requirements.txt
