version: 2

formats:
  - htmlzip

sphinx:
  configuration: docs/conf.py

build:
  os: ubuntu-24.04
  tools:
    python: "3.13"

  apt_packages:
    - graphviz

  jobs:
    post_checkout:
      - (git --no-pager log --pretty="tformat:%s -- %b" -1 | grep -viq "skip ci") || exit 183
      - |
        if [ "$READTHEDOCS_VERSION_TYPE" = "external" ] && git diff --quiet origin/main -- docs/ python/ .readthedocs.yaml;
        then
          exit 183;
        fi
      - git fetch --unshallow --tags

    pre_build:
      # Install uv
      - asdf plugin add uv
      - asdf install uv latest
      - asdf global uv latest

      # Install *only* documentation dependencies
      - uv sync --frozen --group docs --no-dev --no-install-project

      # Make Python sources importable without building
      - export PYTHONPATH=$PWD/python

    build:
      html:
        - uv run --no-project -m sphinx -T -b html -d docs/_build/doctrees docs $READTHEDOCS_OUTPUT/html

      htmlzip:
        - uv run --no-project -m sphinx -T -b dirhtml -d docs/_build/doctrees docs docs/_build/dirhtml
        - mkdir -p $READTHEDOCS_OUTPUT/htmlzip
        - zip -r $READTHEDOCS_OUTPUT/htmlzip/html.zip docs/_build/dirhtml/*
